on:
  push:
    branches:
      - main
  release:
    types:
      - created

name: npm

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build && cp -r bin dist
      - name: Publish
        uses: menduz/oddish-action@2.0.1
        with:
          scope: dcl
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
